name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os:
          - windows-2019
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: kscript
          version: 3.1.0

      - name: Install tox
        run: |
          pip3 --version
          pip3 install setuptools tox

      - name: Install dependencies for ${{ runner.os }}.
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install --yes astyle
              curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint
              chmod a+x ktlint
              sudo mv ktlint /usr/local/bin/
              (cd /usr/local/bin && sudo ln -s $(find ~/.julia -name format.jl))
              (cd /usr/local/bin && sudo ln -s $HOME/go/bin/golint)
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew tap holgerbrandl/tap https://github.com/holgerbrandl/homebrew-tap
              brew install clang-format kscript ktlint astyle
              (cd /usr/local/bin && ln -s $(find ~/.julia -name format.jl))
              (cd /usr/local/bin && ln -s $HOME/go/bin/golint)
          elif [ "$RUNNER_OS" == "Windows" ]; then
              ls .
          fi

      - name: Run tox
        shell: bash
        # sdkman init can be replaced with actions setup when the following is fixed
        # https://github.com/sdkman/sdkman-action/issues/8
        run: |
          LINT=1
          if [ "$RUNNER_OS" == "Windows" ]; then
            export PATH="$PATH:/C/Program Files/LLVM/bin"
          fi
          tox -e py38 -- -k 'kotlin'

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linters
        run: pip install black pyflakes cpplint

      - name: Run black
        run: black --check */ *.py

      - name: Remove tests/cases/*.py
        run: rm tests/cases/*.py

      - name: Run pyflakes
        run: pyflakes */ *.py

      - name: Run cpplint
        run: cpplint --filter=-legal/copyright tests/expected/*.cpp