name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install tox
        run: pip3 install tox

      - name: Install ${{ runner.os }} dependencies.
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint
              chmod a+x ktlint
              sudo mv ktlint /usr/local/bin/
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew tap holgerbrandl/tap https://github.com/holgerbrandl/homebrew-tap
              brew install clang-format kscript ktlint
          elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install zip curl
          fi
          dart pub global activate stagehand
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kscript

      - name: Install dart sprintf
        shell: bash
        run: |
          (cd tests && dart pub global run stagehand:stagehand --override package-simple && dart pub add sprintf)

      - name: Install rust-script and cargo-script
        run: cargo install rust-script cargo-script

      - name: Run tox
        run: tox

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linters
        run: pip install black pyflakes

      - name: Remove tests/cases/*.py
        run: rm tests/cases/*.py

      - name: Run black
        run: black */ *.py

      - name: Run pyflakes
        run: pyflakes */ *.py
