name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Check for runner dependencies
        shell: bash
        run: |
          echo "WHICH_V=$(which v 2>/dev/null)" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 15

      - name: Add missing dependencies on act Medium runner
        if: ${{ env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
              cargo \
              clang-12 \
              clang-format \
              powershell \
              rustfmt \
            && true
          echo "::add-path::${HOME}/.cargo/bin/"

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: julia-actions/setup-julia@v1
      - uses: fwilhe2/setup-kotlin@main
      - uses: jiro4989/setup-nim-action@v1
      - uses: actions/setup-go@v2
        # Needed as https://github.com/actions/setup-go/pull/89 is not merged
        with:
          go-version: '1.15'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: kscript
          version: 3.1.0

      - name: Install V
        if: ${{ !env.WHICH_V }}
        shell: bash
        env:
          RELEASE: weekly.2021.29
        run: |
          FILE=v_$(echo ${RUNNER_OS} | tr '[:upper:]' '[:lower:]').zip
          (cd /tmp && curl -sSLO https://github.com/vlang/v/releases/download/${RELEASE}/${FILE})
          (cd /tmp && unzip ${FILE})
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "::add-path::/tmp/v"
          else
            (cd /usr/local/bin && sudo ln -s /tmp/v/v)
          fi

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Install go packages
        shell: bash
        run: |
          go get github.com/hgfischer/go-iter
          go get github.com/google/go-cmp/cmp
          go get github.com/adsharma/py2many/pygo/runtime
          go get github.com/mgechev/revive
          if [[ -d /usr/local/bin && ! -f /usr/local/bin/golint && -f $HOME/go/bin/golint ]]; then
            (cd /usr/local/bin && sudo ln -fs $HOME/go/bin/golint)
          fi

      - name: Install tox
        run: |
          pip3 --version
          pip3 install setuptools tox

      - name: Install Julia packages
        shell: bash
        run: |
          julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using Pkg; Pkg.add("SuperEnum")'
          if [[ -d /usr/local/bin && ! -f /usr/local/bin/format.jl ]]; then
            (cd /usr/local/bin && sudo ln -fs $(find ~/.julia -name format.jl))
          fi

      - name: Install dependencies for ${{ runner.os }}.
        shell: bash
        run: |
          set -ex
          which v ||:
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install --yes \
                  astyle \
                  libc++-12-dev \
                  libc++abi-12-dev \
                  z3 \
                && true
              echo "CXX=clang++-12" >> $GITHUB_ENV
              curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint
              chmod a+x ktlint
              sudo mv ktlint /usr/local/bin/
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew tap holgerbrandl/tap https://github.com/holgerbrandl/homebrew-tap
              brew install astyle clang-format cljstyle ktlint z3
          elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install zip curl astyle llvm
          fi
          echo "WHICH_CLJSTYLE=$(which cljstyle 2>/dev/null)" >> $GITHUB_ENV

      - name: Install dart dependencies
        shell: bash
        run: |
          dart --version
          # tests/build here must be the same as defined in test_cli
          if [[ ! -d tests/build ]]; then
            dart create --no-pub -t package-simple tests/build
          fi
          cd tests/build
          if ! grep vnum pubspec.yaml ; then
            # Specifying the version here doesnt stick
            set -ex
            dart pub add collection:1.15.0
            cat pubspec.yaml
            dart pub add sprintf
            dart pub add tuple
            cat pubspec.yaml
            sed -i.bak '/test:/d' pubspec.yaml
            # Force version downgrade here
            sed -i.bak 's:1.16.0:1.15.0:' pubspec.yaml
            flutter pub add vnum
          fi

      - name: Install cargo-script
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-script

      - name: Install smt dependency cljstyle (Linux)
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            (curl -sLO https://raw.githubusercontent.com/greglook/cljstyle/main/script/install-cljstyle
             sed -i.bak 's/--overwrite//' install-cljstyle
             chmod +x install-cljstyle
             sudo ./install-cljstyle)
          fi

      - name: Run tox
        shell: bash
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          if [ "$RUNNER_OS" == "Windows" ]; then
            export PATH="/tmp/v"
          fi
          tox

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linters
        run: pip install black pyflakes cpplint

      - name: Remove tests/cases/*.py & tests/expected/*.py
        run: rm tests/cases/*.py tests/expected/*.py tests/dir_cases/test1-*-expected/*.py

      - name: Run black
        run: black --check */ *.py

      - name: Run pyflakes
        run: pyflakes */ *.py

      - name: Run cpplint
        run: cpplint --filter=-legal/copyright,-whitespace/semicolon,-runtime/reference tests/expected/*.cpp
